# Generated by Django 2.2.7 on 2019-11-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarID', models.CharField(max_length=255)),
                ('BarName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewID', models.CharField(max_length=255)),
                ('Rating', models.IntegerField()),
                ('FavoriteDrink', models.TextField()),
                ('Food', models.TextField()),
                ('Atmosphere', models.TextField()),
                ('Overall', models.IntegerField()),
                ('BarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bar')),
            ],
        ),
    ]
