# Generated by Django 2.2.7 on 2019-11-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='BarID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ReviewID',
        ),
    ]
