# Generated by Django 2.2.7 on 2019-11-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191121_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='BarID',
            new_name='Bar',
        ),
    ]
