# Generated by Django 2.2.7 on 2019-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191121_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Overall',
            new_name='Drinks',
        ),
        migrations.RemoveField(
            model_name='review',
            name='FavoriteDrink',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Food',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='Atmosphere',
            field=models.IntegerField(),
        ),
    ]
