# Generated by Django 2.2.7 on 2019-11-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191125_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Food',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
