# Generated by Django 2.2.7 on 2019-11-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Comment',
            field=models.TextField(default=''),
        ),
    ]
